export const kurwa = {
    docs: [
    {
    doctype: "DocType",
    name: "kurwa",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 0,
    issingle: 0,
    is_tree: 0,
    istable: 0,
    editable_grid: 0,
    track_changes: 0,
    module: "Drive7",
    naming_rule: "",
    sort_field: "modified",
    sort_order: "DESC",
    read_only: 0,
    in_create: 0,
    allow_copy: 0,
    allow_rename: 1,
    allow_import: 0,
    hide_toolbar: 0,
    track_seen: 0,
    max_attachments: 0,
    document_type: "",
    engine: "InnoDB",
    is_submittable: 1,
    show_name_in_global_search: 0,
    custom: 1,
    beta: 0,
    has_web_view: 0,
    allow_guest_to_view: 0,
    email_append_to: 0,
    show_title_field_in_link: 0,
    translated_doctype: 0,
    is_calendar_and_gantt: 0,
    quick_entry: 0,
    track_views: 0,
    is_virtual: 0,
    queue_in_background: 0,
    allow_events_in_timeline: 0,
    allow_auto_repeat: 0,
    make_attachments_public: 0,
    force_re_route_to_default_view: 0,
    show_preview_popup: 0,
    index_web_pages_for_search: 1,
    fields: [
    {
    doctype: "DocField",
    name: "72a4db8fe1",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 1,
    fieldname: "section_break_fiks",
    fieldtype: "Section Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "aa09c28cde",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 2,
    fieldname: "attach_utln",
    label: "Attach",
    fieldtype: "Attach",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "53dc8526b4",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 3,
    fieldname: "attach_image_kphq",
    label: "Attach Image",
    fieldtype: "Attach Image",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "88356b3521",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 4,
    fieldname: "autocomplete_otbl",
    label: "Autocomplete",
    fieldtype: "Autocomplete",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "07ef747a98",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 5,
    fieldname: "check_xbsx",
    label: "checkbox",
    fieldtype: "Check",
    options: "kurwa\njebani\nque",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    default: "0",
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "0245a8271a",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 6,
    fieldname: "color_bpvx",
    label: "color",
    fieldtype: "Color",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "740dc6480e",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 7,
    fieldname: "duration_ktzq",
    label: "duration",
    fieldtype: "Duration",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "25b9a682dc",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 8,
    fieldname: "date_xqhc",
    label: "Date",
    fieldtype: "Date",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "8bb859d7ee",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 9,
    fieldname: "datetime_hedx",
    label: "Date Time",
    fieldtype: "Datetime",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "12d5f58952",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 10,
    fieldname: "currency_dlmh",
    label: "Currency",
    fieldtype: "Currency",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "11d1b166f5",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 11,
    fieldname: "column_break_rulw",
    label: "",
    fieldtype: "Column Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "b748ed618c",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 12,
    fieldname: "data_sfoc",
    label: "Data",
    fieldtype: "Data",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "df495fa22f",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 13,
    fieldname: "long_text_pgry",
    label: "Long Text",
    fieldtype: "Long Text",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "4aefe256d8",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 14,
    fieldname: "section_break_ztpq",
    label: "",
    fieldtype: "Section Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "a5e4587f90",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 15,
    fieldname: "code_aibs",
    label: "Code editor",
    fieldtype: "Code",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "155c554883",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 16,
    fieldname: "html_editor_ujvy",
    label: "HTML Editor",
    fieldtype: "HTML Editor",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "3d6753a323",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 17,
    fieldname: "currency_mgch",
    label: "Currency",
    fieldtype: "Currency",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "50e4d04c4c",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 18,
    fieldname: "float_xarh",
    label: "Float",
    fieldtype: "Float",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "fbd80e709b",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 19,
    fieldname: "int_fhpe",
    label: "Integer",
    fieldtype: "Int",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "fa702582d5",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 20,
    fieldname: "password_jeng",
    label: "Password",
    fieldtype: "Password",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "5bd66ada6e",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 21,
    fieldname: "amended_from",
    label: "Amended From",
    fieldtype: "Link",
    options: "kurwa",
    search_index: 1,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 1,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 1,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 1,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    linked_document_type: "",
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null
    },
    {
    doctype: "DocField",
    name: "03b3f83049",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 22,
    fieldname: "phone_ordl",
    label: "Phone",
    fieldtype: "Phone",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "a53c765a35",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 23,
    fieldname: "percent_bwlr",
    label: "Percent",
    fieldtype: "Percent",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    }
    ],
    permissions: [
    {
    doctype: "DocPerm",
    name: "409cecfc0e",
    creation: "2024-05-29 23:54:57.647197",
    modified: "2024-05-30 01:54:51.464982",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "kurwa",
    parentfield: "permissions",
    parenttype: "DocType",
    idx: 1,
    permlevel: 0,
    role: "System Manager",
    read: 1,
    write: 1,
    create: 1,
    submit: 1,
    cancel: 0,
    delete: 1,
    amend: 0,
    report: 1,
    export: 1,
    import: 0,
    share: 1,
    print: 1,
    email: 1,
    if_owner: 0,
    select: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ]
    }
    ],
    actions: [ ],
    links: [ ],
    states: [ ],
    __js: null,
    __css: null,
    __list_js: null,
    __calendar_js: null,
    __map_js: null,
    __linked_with: null,
    __messages: null,
    __print_formats: [ ],
    __workflow_docs: [ ],
    __form_grid_templates: null,
    __listview_template: null,
    __tree_js: null,
    __dashboard: {
    transactions: [ ],
    non_standard_fieldnames: { },
    internal_links: { }
    },
    __kanban_column_fields: [ ],
    __templates: null
    }
    ],
}
