export const testDoc = {
    docs: [
    {
    doctype: "DocType",
    name: "TestDoc",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 0,
    issingle: 0,
    is_tree: 0,
    istable: 0,
    editable_grid: 0,
    track_changes: 0,
    module: "Drive7",
    naming_rule: "",
    sort_field: "modified",
    sort_order: "DESC",
    read_only: 0,
    in_create: 0,
    allow_copy: 0,
    allow_rename: 1,
    allow_import: 0,
    hide_toolbar: 0,
    track_seen: 0,
    max_attachments: 0,
    document_type: "",
    engine: "InnoDB",
    is_submittable: 0,
    show_name_in_global_search: 0,
    custom: 0,
    beta: 0,
    has_web_view: 0,
    allow_guest_to_view: 0,
    email_append_to: 0,
    show_title_field_in_link: 0,
    translated_doctype: 0,
    is_calendar_and_gantt: 0,
    quick_entry: 0,
    track_views: 0,
    is_virtual: 0,
    queue_in_background: 0,
    allow_events_in_timeline: 0,
    allow_auto_repeat: 0,
    make_attachments_public: 0,
    force_re_route_to_default_view: 0,
    show_preview_popup: 0,
    index_web_pages_for_search: 1,
    fields: [
    {
    doctype: "DocField",
    name: "5b547a2559",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 1,
    fieldname: "attach",
    label: "Attach",
    fieldtype: "Attach",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "beb62f745a",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 2,
    fieldname: "attach_image",
    label: "Attach Image",
    fieldtype: "Attach Image",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "abdcc0fd77",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 3,
    fieldname: "autocomplete",
    label: "Autocomplete",
    fieldtype: "Autocomplete",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "1cca63b7a9",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 4,
    fieldname: "barcode",
    label: "Barcode",
    fieldtype: "Barcode",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "b35dcb958a",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 5,
    fieldname: "button",
    label: "Button",
    fieldtype: "Button",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "67ce5162ff",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 6,
    fieldname: "check",
    label: "Check",
    fieldtype: "Check",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    default: "0",
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "13f4e619fa",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 7,
    fieldname: "code",
    label: "Code",
    fieldtype: "Code",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "c01fd728bf",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 8,
    fieldname: "color",
    label: "Color",
    fieldtype: "Color",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "b4b53c486c",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 9,
    fieldname: "currency",
    label: "Currency",
    fieldtype: "Currency",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "24f97c80c1",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 10,
    fieldname: "data",
    label: "Data",
    fieldtype: "Data",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "bde90e2fe9",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 11,
    fieldname: "date",
    label: "Date",
    fieldtype: "Date",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "b72e212e94",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 12,
    fieldname: "datetime",
    label: "Datetime",
    fieldtype: "Datetime",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "29ead2c643",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 13,
    fieldname: "duration",
    label: "Duration",
    fieldtype: "Duration",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "e21cbb7766",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 14,
    fieldname: "link",
    label: "Link",
    fieldtype: "Link",
    options: "User",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    default: "",
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: [
    "full_name"
    ],
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "fba264f886",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 15,
    fieldname: "dl_doc",
    label: "Dynamic Link Doc",
    fieldtype: "Link",
    options: "DocType",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    linked_document_type: "Document",
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: [
    "module"
    ],
    is_custom_field: null
    },
    {
    doctype: "DocField",
    name: "dec2466510",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 16,
    fieldname: "dynamic_link",
    label: "Dynamic Link",
    fieldtype: "Dynamic Link",
    options: "dl_doc",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    default: "User",
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "9fab5d2de9",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 17,
    fieldname: "float",
    label: "Float",
    fieldtype: "Float",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "79f78b9aeb",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 18,
    fieldname: "geolocation",
    label: "Geolocation",
    fieldtype: "Geolocation",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "cf308a4bfc",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 19,
    fieldname: "heading",
    label: "Heading",
    fieldtype: "Heading",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "f6af482ab0",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 20,
    fieldname: "html",
    label: "Html",
    fieldtype: "HTML",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "305c39af93",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 21,
    fieldname: "html_editor",
    label: "Html Editor",
    fieldtype: "HTML Editor",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "815aac8417",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 22,
    fieldname: "icon",
    label: "Icon",
    fieldtype: "Icon",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "a329d1c7c0",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 23,
    fieldname: "image",
    label: "Image",
    fieldtype: "Image",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "081f476a7c",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 24,
    fieldname: "int",
    label: "Int",
    fieldtype: "Int",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "10cd2997c1",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 25,
    fieldname: "json",
    label: "Json",
    fieldtype: "JSON",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "43f469faf2",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 26,
    fieldname: "long_text",
    label: "Long Text",
    fieldtype: "Long Text",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "7053d80739",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 27,
    fieldname: "markdown_editor",
    label: "Markdown Editor",
    fieldtype: "Markdown Editor",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "91fdd84a1d",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 28,
    fieldname: "password",
    label: "Password",
    fieldtype: "Password",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "2d7b350f7d",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 29,
    fieldname: "percent",
    label: "Percent",
    fieldtype: "Percent",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "faefed17fe",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 30,
    fieldname: "phone",
    label: "Phone",
    fieldtype: "Phone",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "ec214bf60d",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 31,
    fieldname: "read_only",
    label: "Read Only",
    fieldtype: "Read Only",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    default: "Mad",
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "22a0a39f19",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 32,
    fieldname: "rating",
    label: "Rating",
    fieldtype: "Rating",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "f2e2593824",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 33,
    fieldname: "select",
    label: "Select",
    fieldtype: "Select",
    options: "1\n2\n3\n4\n5",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "3199453e3c",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 34,
    fieldname: "signature",
    label: "Signature",
    fieldtype: "Signature",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "9cb3af99bd",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 35,
    fieldname: "small_text",
    label: "Small Text",
    fieldtype: "Small Text",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "9c5840cb1a",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 36,
    fieldname: "table",
    label: "Table",
    fieldtype: "Table",
    options: "About Us Team Member",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "bd2aee8b26",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 37,
    fieldname: "table_multiselect",
    label: "Table MultiSelect",
    fieldtype: "Table MultiSelect",
    options: "Production Plan Material Request Warehouse",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "521804d98f",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 38,
    fieldname: "text",
    label: "Text",
    fieldtype: "Text",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "ee5ca6214c",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 39,
    fieldname: "text_editor",
    label: "Text Editor",
    fieldtype: "Text Editor",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "b38e6e6915",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 40,
    fieldname: "time",
    label: "Time",
    fieldtype: "Time",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "0583d4d56e",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 41,
    fieldname: "s2_section",
    label: "S2",
    fieldtype: "Section Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "313ba15a36",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 42,
    fieldname: "c2",
    label: "",
    fieldtype: "Column Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "801ab9fb90",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 43,
    fieldname: "d1",
    label: "d1",
    fieldtype: "Data",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "eb940e0e76",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 44,
    fieldname: "c3",
    label: "",
    fieldtype: "Column Break",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "55644feae8",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 45,
    fieldname: "d2",
    label: "d2",
    fieldtype: "Data",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    }
    ],
    permissions: [
    {
    doctype: "DocPerm",
    name: "ea148b070d",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "permissions",
    parenttype: "DocType",
    idx: 1,
    permlevel: 0,
    role: "System Manager",
    read: 1,
    write: 1,
    create: 1,
    submit: 0,
    cancel: 0,
    delete: 1,
    amend: 0,
    report: 1,
    export: 1,
    import: 0,
    share: 1,
    print: 1,
    email: 1,
    if_owner: 0,
    select: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ]
    }
    ],
    _table_fields: [
    {
    doctype: "DocField",
    name: "9c5840cb1a",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 36,
    fieldname: "table",
    label: "Table",
    fieldtype: "Table",
    options: "About Us Team Member",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ]
    },
    {
    doctype: "DocField",
    name: "bd2aee8b26",
    creation: "2024-05-26 12:26:29.769839",
    modified: "2024-05-26 12:44:15.255319",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "TestDoc",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 37,
    fieldname: "table_multiselect",
    label: "Table MultiSelect",
    fieldtype: "Table MultiSelect",
    options: "Production Plan Material Request Warehouse",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 0,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    precision: "",
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ]
    }
    ],

    actions: [ ],
    links: [ ],
    states: [ ],
    __css: null,
    __list_js: null,
    __calendar_js: null,
    __map_js: null,
    __linked_with: null,
    __messages: null,
    __print_formats: [ ],
    __workflow_docs: [ ],
    __form_grid_templates: null,
    __listview_template: null,
    __tree_js: null,
    __dashboard: {
    transactions: [ ],
    non_standard_fieldnames: { },
    internal_links: { }
    },
    __kanban_column_fields: [ ],
    __templates: null
    },
    {
    doctype: "DocType",
    name: "About Us Team Member",
    creation: "2013-03-07 11:55:11",
    modified: "2022-08-03 12:20:50.254472",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 1,
    issingle: 0,
    is_tree: 0,
    istable: 1,
    editable_grid: 1,
    track_changes: 0,
    module: "Website",
    sort_field: "modified",
    sort_order: "DESC",
    read_only: 0,
    in_create: 0,
    allow_copy: 0,
    allow_rename: 0,
    allow_import: 0,
    hide_toolbar: 0,
    track_seen: 0,
    max_attachments: 0,
    engine: "InnoDB",
    is_submittable: 0,
    show_name_in_global_search: 0,
    custom: 0,
    beta: 0,
    has_web_view: 0,
    allow_guest_to_view: 0,
    email_append_to: 0,
    show_title_field_in_link: 0,
    migration_hash: "1662f59237b66012e7e608e489863d10",
    translated_doctype: 0,
    is_calendar_and_gantt: 0,
    quick_entry: 0,
    track_views: 0,
    is_virtual: 0,
    queue_in_background: 0,
    allow_events_in_timeline: 0,
    allow_auto_repeat: 0,
    make_attachments_public: 0,
    force_re_route_to_default_view: 0,
    show_preview_popup: 0,
    index_web_pages_for_search: 0,
    fields: [
    {
    doctype: "DocField",
    name: "db792e6952",
    creation: "2013-03-07 11:55:11",
    modified: "2024-01-29 14:08:51.438117",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "About Us Team Member",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 1,
    fieldname: "full_name",
    label: "Full Name",
    fieldtype: "Data",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    width: "150px",
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "6d3c861b31",
    creation: "2013-03-07 11:55:11",
    modified: "2024-01-29 14:08:51.438117",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "About Us Team Member",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 2,
    fieldname: "image_link",
    label: "Image Link",
    fieldtype: "Attach",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    width: "150px",
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    },
    {
    doctype: "DocField",
    name: "53e867f7dd",
    creation: "2013-03-07 11:55:11",
    modified: "2024-01-29 14:08:51.438117",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "About Us Team Member",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 3,
    fieldname: "bio",
    label: "Bio",
    fieldtype: "Small Text",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 1,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    width: "200px",
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null,
    linked_document_type: null
    }
    ],
    __assets_loaded: true,
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    __js: null,
    __css: null,
    __list_js: null,
    __calendar_js: null,
    __map_js: null,
    __linked_with: null,
    __messages: null,
    __print_formats: null,
    __workflow_docs: null,
    __form_grid_templates: null,
    __listview_template: null,
    __tree_js: null,
    __dashboard: null,
    __kanban_column_fields: null,
    __templates: null,
    __custom_js: null,
    __custom_list_js: null
    },
    {
    doctype: "DocType",
    name: "Production Plan Material Request Warehouse",
    creation: "2020-02-02 10:37:16.650836",
    modified: "2020-10-26 12:55:00.778201",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 0,
    issingle: 0,
    is_tree: 0,
    istable: 1,
    editable_grid: 1,
    track_changes: 1,
    module: "Manufacturing",
    sort_field: "modified",
    sort_order: "DESC",
    read_only: 0,
    in_create: 0,
    allow_copy: 0,
    allow_rename: 0,
    allow_import: 0,
    hide_toolbar: 0,
    track_seen: 0,
    max_attachments: 0,
    engine: "InnoDB",
    is_submittable: 0,
    show_name_in_global_search: 0,
    custom: 0,
    beta: 0,
    has_web_view: 0,
    allow_guest_to_view: 0,
    email_append_to: 0,
    show_title_field_in_link: 0,
    migration_hash: "f9debc82c07cc3656f30c4e01caced3f",
    translated_doctype: 0,
    is_calendar_and_gantt: 0,
    quick_entry: 1,
    track_views: 0,
    is_virtual: 0,
    queue_in_background: 0,
    allow_events_in_timeline: 0,
    allow_auto_repeat: 0,
    make_attachments_public: 0,
    force_re_route_to_default_view: 0,
    show_preview_popup: 0,
    index_web_pages_for_search: 1,
    fields: [
    {
    doctype: "DocField",
    name: "c343f6e36f",
    creation: "2020-02-02 10:37:16.650836",
    modified: "2024-01-29 14:20:33.228605",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    parent: "Production Plan Material Request Warehouse",
    parentfield: "fields",
    parenttype: "DocType",
    idx: 1,
    fieldname: "warehouse",
    label: "Warehouse",
    fieldtype: "Link",
    options: "Warehouse",
    search_index: 0,
    show_dashboard: 0,
    hidden: 0,
    set_only_once: 0,
    allow_in_quick_entry: 0,
    print_hide: 0,
    report_hide: 0,
    reqd: 0,
    bold: 0,
    in_global_search: 0,
    collapsible: 0,
    unique: 0,
    no_copy: 0,
    allow_on_submit: 0,
    show_preview_popup: 0,
    permlevel: 0,
    ignore_user_permissions: 0,
    columns: 0,
    in_list_view: 1,
    fetch_if_empty: 0,
    in_filter: 0,
    remember_last_selected_value: 0,
    ignore_xss_filter: 0,
    print_hide_if_no_value: 0,
    allow_bulk_edit: 0,
    in_standard_filter: 0,
    in_preview: 0,
    read_only: 0,
    length: 0,
    translatable: 0,
    hide_border: 0,
    hide_days: 0,
    hide_seconds: 0,
    non_negative: 0,
    is_virtual: 0,
    sort_options: 0,
    linked_document_type: "Setup",
    fields: [ ],
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    search_fields: null,
    is_custom_field: null
    }
    ],
    __assets_loaded: true,
    permissions: [ ],
    actions: [ ],
    links: [ ],
    states: [ ],
    __js: null,
    __css: null,
    __list_js: null,
    __calendar_js: null,
    __map_js: null,
    __linked_with: null,
    __messages: null,
    __print_formats: null,
    __workflow_docs: null,
    __form_grid_templates: null,
    __listview_template: null,
    __tree_js: null,
    __dashboard: null,
    __kanban_column_fields: null,
    __templates: null,
    __custom_js: null,
    __custom_list_js: null
    }
    ],
    user_settings: '{"last_view": "List", "List": {"filters": [], "sort_by": "modified", "sort_order": "desc"}, "updated_on": "Wed May 29 2024 18:36:41 GMT+0300", "GridView": {"About Us Team Member": [{"fieldname": "full_name", "columns": 2}, {"fieldname": "image_link", "columns": 2}, {"fieldname": "bio", "columns": 3}]}}',
    }